package com.github.tomasjuan007.policycenter.dal.model;

import java.util.Date;

public class TbRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.id
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.rule_id
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private Long ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.app
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private String app;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.name
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.val
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private String val;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.op
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private String op;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.lft
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private Long lft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.rgt
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private Long rgt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.lvl
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private Long lvl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.is_deleted
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.created_at
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_rule.updated_at
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.id
     *
     * @return the value of tb_rule.id
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.id
     *
     * @param id the value for tb_rule.id
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.rule_id
     *
     * @return the value of tb_rule.rule_id
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.rule_id
     *
     * @param ruleId the value for tb_rule.rule_id
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.app
     *
     * @return the value of tb_rule.app
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.app
     *
     * @param app the value for tb_rule.app
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setApp(String app) {
        this.app = app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.name
     *
     * @return the value of tb_rule.name
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.name
     *
     * @param name the value for tb_rule.name
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.val
     *
     * @return the value of tb_rule.val
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.val
     *
     * @param val the value for tb_rule.val
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setVal(String val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.op
     *
     * @return the value of tb_rule.op
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public String getOp() {
        return op;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.op
     *
     * @param op the value for tb_rule.op
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setOp(String op) {
        this.op = op;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.lft
     *
     * @return the value of tb_rule.lft
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public Long getLft() {
        return lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.lft
     *
     * @param lft the value for tb_rule.lft
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setLft(Long lft) {
        this.lft = lft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.rgt
     *
     * @return the value of tb_rule.rgt
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public Long getRgt() {
        return rgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.rgt
     *
     * @param rgt the value for tb_rule.rgt
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setRgt(Long rgt) {
        this.rgt = rgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.lvl
     *
     * @return the value of tb_rule.lvl
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public Long getLvl() {
        return lvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.lvl
     *
     * @param lvl the value for tb_rule.lvl
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setLvl(Long lvl) {
        this.lvl = lvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.is_deleted
     *
     * @return the value of tb_rule.is_deleted
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.is_deleted
     *
     * @param isDeleted the value for tb_rule.is_deleted
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.created_at
     *
     * @return the value of tb_rule.created_at
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.created_at
     *
     * @param createdAt the value for tb_rule.created_at
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_rule.updated_at
     *
     * @return the value of tb_rule.updated_at
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_rule.updated_at
     *
     * @param updatedAt the value for tb_rule.updated_at
     *
     * @mbg.generated Thu Jan 07 21:15:39 CST 2021
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}